
orbs:
  rn: react-native-community/react-native@5.4.0
  ruby: circleci/ruby@1.1.2
  android: circleci/android@1.0.3
version: 2.1

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Git submodule update
          command: git submodule update --init --recursive
      - persist_to_workspace:
          paths: .
          root: .

  analyse_js:
    executor: rn/linux_android
    # parallelism: 5
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Jest
          command: |
            TESTS=$(circleci tests glob "app/**/*.test.{ts,tsx}" | circleci tests split)
            yarn ci:test:jest --findRelatedTests $TESTS
      - persist_to_workspace:
          paths: .
          root: .

  decrypt_keystore:
    executor: rn/linux_android 
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Decrypt keystore file
          command: gpg -d --pinentry-mode loopback --batch --yes --passphrase="$ENCRYPTION_PASSPHRASE" --output android/app/punchline.keystore --decrypt android/app/punchline-keys/punchline.keystore.gpg
      - run: 
          name: Copy keystore to fastlane directory
          command: cp android/app/punchline.keystore android/fastlane/release.keystore 
      - persist_to_workspace:
          paths: .
          root: .
      
  build_android_debug:
    executor: rn/linux_android
    resource_class: medium+
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Fastlane Build Debug - Android"
          working_directory: android
          no_output_timeout: 30m
          command: |
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
            gem install bundler
            bundle install
            bundle exec fastlane build_android_debug
      - store_artifacts:
          path: android/app/build/outputs/apk/debug
     
  build_android_release:
    executor: rn/linux_android
    resource_class: medium+
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: "Fastlane Build Release - Android"
          working_directory: android
          no_output_timeout: 30m
          command: |
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
            gem install bundler
            bundle install
            bundle exec fastlane build_android_release_bundle
      - store_artifacts:
          path: android/app/build/outputs/bundle/release

  build_ios_release:
    macos:
      xcode: 12.4.0
    steps:
      - checkout
      - run: 
          name: "Fastlane Build Release - iOS"
          working_directory: ios
          no_output_timeout: 30m
          command: |
            bundle exec fastlane build_ios
      - store_artifacts:
          path: ios/output
  
  e2e_android_debug:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm i -g yarn
      - rn/yarn_install
      - android/create-avd:
          avd-name: android_29_avd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: android_29_avd
          no-window: true
          restore-gradle-cache-prefix: v1a
          post-emulator-launch-assemble-command: ''
      - run:
          name: Start Metro Packager (Background)
          background: true
          command: npm run start
      - run: 
          name: "Fastlane Build Release - Android"
          working_directory: android
          no_output_timeout: 30m
          command: |
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
            gem install bundler
            bundle install
            bundle exec fastlane e2e_debug
      - android/save-gradle-cache:
          cache-prefix: v1a

workflows:
  # Only runs on the develop branch 
  develop:
    jobs: 
      # Checkout the code and persist to the Workspace
      - checkout_code:
          filters:
            branches:
              only:
                - develop
      # Analyze the Javascript using ESLint, and Jest
      # - analyse_js:
      #     requires:
      #       - checkout_code
      # Builds debug android apk
      # - build_android_debug:
      #     requires:
      #         - checkout_code
      #         - analyse_js
      # - e2e_android_debug:
      #     requires: 
      #         - build_android_debug
      # - decrypt_keystore:
      #     requires:
      #       - e2e_android_debug
      # Builds android aab
      # - build_android_release:
      #     requires:
      #         - decrypt_keystore
      #         - e2e_android_debug
      # Build and test the iOS app in release mode
      - rn/ios_build_and_test:
          yarn_cache: true
          yarn_cache_folder: "~/.cache/yarn"          
          xcodebuild_cache: false
          homebrew_cache: false
          project_type: "workspace"
          project_path: "ios/punchline.xcworkspace"
          device: "iPhone 11"
          build_configuration: "Release"
          scheme: "punchline"
          detox_configuration: "ios.sim.release"
          requires:
            - checkout_code
            # - analyse_js

  # Only runs on the master branch 
  # master:
  #   jobs: 
  #     # Checkout the code and persist to the Workspace
  #     - checkout_code:
  #         filters:
  #           branches:
  #             only:
  #               - master
  #           tags:
  #             only: /^v.*/
      
  #     - update_homebrew:
  #         filters:
  #           branches:
  #             only:
  #               - master
  #           tags:
  #             only: /^v.*/

  #     # Analyze the Javascript using ESLint, and Jest
  #     - analyse_js:
  #         requires:
  #           - checkout_code

  #     - decrypt_keystore:
  #         requires:
  #           - checkout_code

  #     # This configures the rn/linux_js for building android
  #     - configure_fastlane_android:
  #         requires:
  #           - analyse_js
  #     # This configures the rn/linux_js for e2e testing
  #     - configure_fastlane_e2e:
  #         requires:
  #           - analyse_js

  #     - build_android_release:
  #         requires:
  #             - configure_fastlane_android
  #             - decrypt_keystore
  #             - configure_fastlane_e2e

  #     - fastlane_e2e_android:
  #         requires:
  #             - build_android_release
  #             - configure_fastlane_android
  #             - configure_fastlane_e2e

  #     # Build and test the iOS app in release mode
  #     # - rn/ios_build_and_test:
  #     #     yarn_cache: false
  #     #     xcodebuild_cache: false
  #     #     homebrew_cache: false
  #     #     project_type: "workspace"
  #     #     project_path: "ios/punchline.xcworkspace"
  #     #     device: "iPhone 11"
  #     #     build_configuration: "Release"
  #     #     scheme: "punchline"
  #     #     detox_configuration: "ios.sim.release"
  #     #     requires:
  #     #       - checkout_code
  #     #       - analyse_js
  #     #       - update_homebrew

  #     # - build_ios_release:
  #     #     requires:
  #     #         - configure_fastlane_android
  #     #         - decrypt_keystore
  #     #         - rn/ios_build_and_test
