jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  
  analyse_js:
    executor: rn/linux_js
    parallelism: 5
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Jest
          command: | 
            TESTS=$(circleci tests glob "app/**/*.test.{ts,tsx}" | circleci tests split)
            yarn ci:test:jest --findRelatedTests $TESTS

  update_homebrew:
    executor: rn/macos
    steps:
      - run:
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew update
          name: Update Homebrew
      - persist_to_workspace:
          paths: .
          root: .
           
  fastlane_android_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run: npm i
      - run:
          command: echo
          name: Run Fastlane
          
  fastlane_ios_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run: npm i
      - run:
          command: echo 1
          name: Run Fastlane

  test_and_build_ios:
    macos:
      xcode: 11.4.0
    steps:
      - checkout
      - run: cd ios && bundle install
      - run: cd ios && bundle exec fastlane testandbuild
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

orbs:
  rn: react-native-community/react-native@5.1.0
version: 2.1
workflows:
  main:
    jobs: 
      # Checkout the code and persist to the Workspace
      - checkout_code:
          filters:
            branches:
              only:
                - master
                - feature/circle-fastlane-init
              ignore:
                - develop
            tags:
              only: /^v.*/
      # Analyze the Javascript using ESLint, and Jest
      - analyse_js:
          requires:
            - checkout_code

      - update_homebrew:
          filters:
            branches:
              only:
                - master
                - feature/circle-fastlane-init
              ignore:
                - develop
            tags:
              only: /^v.*/

      # Build the Android app in debug mode
      # - rn/android_build:
      #     yarn_cache: false
      #     name: build_android_debug
      #     project_path: "android"
      #     build_type: debug
      #     requires:
      #       - analyse_js

      # Build and test the Android app in release mode
      # Note: We split these into seperate jobs because we can build the Android app on a Linux machine and preserve the expensive MacOS executor minutes for when it's required
      # - rn/android_build:
      #     yarn_cache: false
      #     name: build_android_release
      #     project_path: "android"
      #     build_type: release
      #     requires:
      #       - analyse_js
      # - rn/android_test:
      #     yarn_cache: false
      #     detox_configuration: "android.emu.release"
      #     requires:
      #       - build_android_release
      
      # Build and test the iOS app in release mode
      - rn/ios_build_and_test:
          yarn_cache: false
          xcodebuild_cache: false
          # homebrew_cache: false
          project_type: "workspace"
          project_path: "ios/punchline.xcworkspace"
          device: "iPhone 11"
          build_configuration: "Release"
          scheme: "punchline"
          detox_configuration: "ios.sim.release"
          requires:
            - checkout_code
            - analyse_js
            - update_homebrew

      # - fastlane_android_release:
          # requires:
            # - rn/android_test
      - test_and_build_ios
      - fastlane_ios_release:
          requires:
            - rn/ios_build_and_test