jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: [.]
          root: .
  
  analyse_js:
    working_directory: ~/punchline
    docker:
      - image: cimg/node:14.16.1

    steps:
      - checkout
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            npm run ci:test:jest
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/punchline
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
  update_homebrew:
    executor: rn/macos
    steps:
      - run:
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew update
          name: Update Homebrew
      - persist_to_workspace:
          paths: .
          root: .
           
  fastlane_android_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run: npm i
      - run:
          command: echo
          name: Run Fastlane
          
  fastlane_ios_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run: npm i
      - run:
          command: echo 1
          name: Run Fastlane
orbs:
  rn: react-native-community/react-native@5.1.0
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code

      - analyse_js:
          requires:
            - checkout_code

      - update_homebrew

      - rn/android_build:
          build_type: debug
          name: build_android_debug
          project_path: android
          requires:
            - analyse_js

      - rn/android_build:
          build_type: release
          name: build_android_release
          project_path: android
          requires:
            - analyse_js

      - rn/android_test:
          detox_configuration: android.emu.release
          requires:
            - build_android_release

      - rn/ios_build_and_test:
          build_configuration: Release
          detox_configuration: ios.sim.release
          device: iPhone X
          project_path: ios/Punchline.xcodeproj
          requires:
            - analyse_js
            - update_homebrew
          scheme: Punchline

      - fastlane_android_release:
          requires:
            - rn/android_test
            
      - fastlane_ios_release:
          requires:
            - rn/ios_build_and_test