
orbs:
  rn: react-native-community/react-native@5.1.0
  ruby: circleci/ruby@1.1.2
version: 2.1

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Git submodule update
          command: git submodule update --init --recursive
      - persist_to_workspace:
          paths: .
          root: .

  configure_fastlane_android: 
    executor: rn/linux_android
    working_directory: android
    steps:
      - attach_workspace:
          at: .
      - run: node -v
      - ruby/install:
          version: '2.7'
      - run: ls -a
      - run:
          name: Setup Environment variables and install gems for fastlane
          command: |
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
            gem install bundler
            bundle install

  configure_fastlane_ios: 
    executor: rn/linux_js
    working_directory: ios
    steps:
      - attach_workspace:
          at: .
      - run: ls -a
      - ruby/install:
          version: '2.7'
      - run:
          name: Setup Environment variables and install gems for fastlane
          command: |
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
            gem install bundler
            bundle install

  analyse_js:
    executor: rn/linux_android
    # parallelism: 5
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Jest
          command: |
            TESTS=$(circleci tests glob "app/**/*.test.{ts,tsx}" | circleci tests split)
            yarn ci:test:jest --findRelatedTests $TESTS
      - persist_to_workspace:
          paths: .
          root: .

  # update_homebrew:
  #   executor: rn/macos
  #   steps:
  #     - run: ls -a
  #     - run:
  #         name: Update homebrew
  #         command: HOMEBREW_NO_AUTO_UPDATE=1 brew update
  #     - persist_to_workspace:
  #         paths: .
  #         root: .

  decrypt_keystore_and_move:
    executor: rn/linux_android 
    steps:
      - attach_workspace:
          at: .
      - run: ls -a
      - run: 
          command: ls android/app
      - run: 
          name: Decrypt keystore file
          command: gpg -d --pinentry-mode loopback --batch --yes --passphrase="$ENCRYPTION_PASSPHRASE" --output android/app/punchline.keystore --decrypt android/app/punchline-keys/punchline.keystore.gpg
      - run: 
          name: Copy keystore to fastlane directory
          command: cp android/app/punchline.keystore android/fastlane/release.keystore 
      - persist_to_workspace:
          paths: .
          root: .
      
  fastlane_build_debug_android:
    executor: rn/linux_android
    steps:
      - attach_workspace:
          at: .
      - run: ls -a
      - run:
          name: "Fastlane Build Debug - Android"
          working_directory: android
          no_output_timeout: 30m
          command: |
            bundle exec fastlane build_android_debug
      - store_artifacts:
          path: android/app/build/outputs/apk/release
     
  fastlane_build_release_android:
    executor: rn/linux_android
    working_directory: android
    steps:
      - attach_workspace:
          at: .
      - run: ls -a
      - ruby/install:
          version: '2.7'
      - run:
          name: "Fastlane Build Release - Android"
          working_directory: android
          no_output_timeout: 30m
          command: |
            bundle exec fastlane build_android_release
      - persist_to_workspace:
          root: .
          paths: .
      - store_artifacts:
          path: android/app/build/outputs/apk/release

  fastlane_e2e_android:
    executor: rn/linux_android
    steps:
      - attach_workspace:
          at: .
      - run: ls -a
      - run:
          name: "Fastlane Build Release - Android"
          working_directory: android
          no_output_timeout: 30m
          command: |
            bundle exec fastlane e2e_release
      - store_artifacts:
          path: .artifacts
          
  # fastlane_build_release_ios:
  #   macos:
  #     xcode: 12.4.0
  #   steps:
  #     - checkout
  #     - run: 
  #         name: "Fastlane Build Release - iOS"
  #         working_directory: ios
  #         no_output_timeout: 30m
  #         command: |
  #           # pod install
  #           bundle exec fastlane build_ios
  #     - store_artifacts:
  #         path: ios/output

workflows:
  develop:
    jobs: 
      # Checkout the code and persist to the Workspace
      - checkout_code:
          filters:
            branches:
              only:
                - develop
                - feature/circle-fastlane-init
      # Analyze the Javascript using ESLint, and Jest
      # - analyse_js:
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - feature/circle-fastlane-init
      #     requires:
      #       - checkout_code
      # Have to do this due to homebrew issues at the moment with their images
      # - update_homebrew:
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - feature/circle-fastlane-init
                
      - decrypt_keystore_and_move:
          requires:
            - checkout_code
      # This configures the rn/linux_js for building android
      - configure_fastlane_android:
          requires:
            - checkout_code
          # requires:
            # - analyse_js
      # This configures the rn/linux_js for e2e testing
      # - configure_fastlane_ios
          # requires:
            # - analyse_js
            # - checkout_code
      # Builds debug android and persists to workspace for e2e testing next
      - fastlane_build_debug_android:
          requires:
              - configure_fastlane_android
              - decrypt_keystore_and_move
      # Runs detox tests on the apk persisted from fastlane_build_debug_android 
      - fastlane_e2e_android:
          requires:
            - fastlane_build_debug_android

      # Build and test the iOS app in release mode
      # - rn/ios_build_and_test:
      #     yarn_cache: false
      #     xcodebuild_cache: false
      #     homebrew_cache: false
      #     project_type: "workspace"
      #     project_path: "ios/punchline.xcworkspace"
      #     device: "iPhone 11"
      #     build_configuration: "Release"
      #     scheme: "punchline"
      #     detox_configuration: "ios.sim.release"
      #     requires:
      #       - checkout_code
      #       - analyse_js
      #       - update_homebrew

  # master:
  #   jobs: 
  #     # Checkout the code and persist to the Workspace
  #     - checkout_code:
  #         filters:
  #           branches:
  #             only:
  #               - master
  #           tags:
  #             only: /^v.*/
      
  #     - update_homebrew:
  #         filters:
  #           branches:
  #             only:
  #               - master
  #           tags:
  #             only: /^v.*/

  #     # Analyze the Javascript using ESLint, and Jest
  #     - analyse_js:
  #         requires:
  #           - checkout_code

  #     - decrypt_keystore_and_move:
  #         requires:
  #           - checkout_code

  #     # This configures the rn/linux_js for building android
  #     - configure_fastlane_android:
  #         requires:
  #           - analyse_js
  #     # This configures the rn/linux_js for e2e testing
  #     - configure_fastlane_e2e:
  #         requires:
  #           - analyse_js

  #     - fastlane_build_release_android:
  #         requires:
  #             - configure_fastlane_android
  #             - decrypt_keystore_and_move
  #             - configure_fastlane_e2e

  #     - fastlane_e2e_android:
  #         requires:
  #             - fastlane_build_release_android
  #             - configure_fastlane_android
  #             - configure_fastlane_e2e

  #     # Build and test the iOS app in release mode
  #     # - rn/ios_build_and_test:
  #     #     yarn_cache: false
  #     #     xcodebuild_cache: false
  #     #     homebrew_cache: false
  #     #     project_type: "workspace"
  #     #     project_path: "ios/punchline.xcworkspace"
  #     #     device: "iPhone 11"
  #     #     build_configuration: "Release"
  #     #     scheme: "punchline"
  #     #     detox_configuration: "ios.sim.release"
  #     #     requires:
  #     #       - checkout_code
  #     #       - analyse_js
  #     #       - update_homebrew

  #     # - fastlane_build_release_ios:
  #     #     requires:
  #     #         - configure_fastlane_android
  #     #         - decrypt_keystore_and_move
  #     #         - rn/ios_build_and_test
