require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
platform :ios, "12.0"

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target "punchline" do
  use_expo_modules!
  post_integrate do |installer|
    expo_patch_react_imports!(installer)
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
# expo-updates doesn't support hermes on ios yet - so hermes is only enabled for android
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end

      case target.name
        when 'RCT-Folly'
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
          end
      end
    end
  end
end
