# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run tests and build the app"
  lane :testandbuild do
    scan
    match(type: "adhoc") # Set type of code signing required
    gym(export_method: "ad-hoc", output_directory: "output") # Directory where signed .ipa file will be placed
  end
end
